version: "3.7"

services:

  php:
      build:
         context: .
         dockerfile: docker/php/Dockerfile
      working_dir: /app
      volumes:
        - .:/app

  db:
      image: mysql:5.7
      volumes:
        - db:/var/lib/mysql
        - ./docker/mysql/entrypoint/:/docker-entrypoint-initdb.d/
      environment:
        - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

volumes:
  db:
