version: "3.7"

services:

  php:
    build:
      context: .
      dockerfile: ./docker/php/production.docker
      args:
        - COMPOSE_PROJECT_NAME
    environment:
      - DB_PASSWORD
      - APP_KEY
      - APP_URL="https://${VIRTUAL_HOST}"
      - COMPOSER_CACHE_DIR=/composer-cache
    command: sh -c "
        /wait-for db:3306
        && php-fpm
      "
    volumes:
      - app:/var/www
      - composer-cache:/composer-cache
      - npm-cache:/root/.npm

  web:
    environment:
      - VIRTUAL_HOST
      - LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL
    networks:
      - frontend
      - backend
    volumes:
      - app:/var/www

volumes:
  app:
  npm-cache:
  composer-cache:

networks:
  frontend:
    external:
      name: nginx-proxy
