version: "3.7"

services:

  php:
    user: "${UID}:${GID}"
    environment:
      - COMPOSER_CACHE_DIR=/var/www/.composer
    volumes:
      - .:/var/www

  web:
    volumes:
      - .:/var/www

  node:
    image: node:13-alpine
    working_dir: /app
    volumes:
      - .:/app
    command: tail -f /dev/null

  dusk:
    volumes:
      - .:/app
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/dusk/Dockerfile
    networks:
      - backend
    command: tail -f /dev/null

volumes:
  composer:
