version: "3.7"

services:

  php:
      build:
         context: .
         dockerfile: ./docker/php/Dockerfile
      command: /wait-for db:3306 -- php-fpm

  db:
      build:
         context: .
         dockerfile: ./docker/db/Dockerfile
      volumes:
        - db:/var/lib/mysql
      environment:
        - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

  web:
      build:
         context: .
         dockerfile: ./docker/web/Dockerfile
      ports:
        - "${DEV_APP_PORT}:80"
      command: /wait-for php:9000 -- nginx -g 'daemon off;'

volumes:
  db:
