version: "3.7"

services:

  php:
    volumes:
      - .:/var/www:rw

  web:
    volumes:
      - .:/var/www:rw

  dusk:
    volumes:
      - .:/app
    working_dir: /app
    build:
      context: .
      dockerfile: ./docker/dusk/Dockerfile
    networks:
      - backend
    command: 'ls -lat'
