version: "3.7"

services:

  php:
      build:
         context: .
         dockerfile: ./docker/php/local.Dockerfile
         args:
           UID: $DEV_UID
      volumes:
        - .:/var/www:rw
        - ./storage:/var/www/storage:rw
        - ./docker/php/php.ini:/usr/local/etc/php/php.ini

  db:
      image: mysql:5.7
      volumes:
        - db:/var/lib/mysql
        - ./docker/db/entrypoint/:/docker-entrypoint-initdb.d/
      environment:
        - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"

  web:
      build:
         context: .
         dockerfile: ./docker/web/Dockerfile
      volumes:
        - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
        - .:/var/www:rw
        - ./docker/wait-for-it.sh:/wait-for-it.sh
      ports:
        - "${DEV_APP_PORT}:80"
      command: sh -c "
        ./wait-for-it.sh 'php:9000' -- nginx -g 'daemon off;'
        "

volumes:
  db:
